package dev.ftcplus.processor;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@SupportedAnnotationTypes({
    "dev.ftcplus.core.TeamRobot",
    "dev.ftcplus.core.Setting",
    "dev.ftcplus.core.Diagnostic"
})
@SupportedSourceVersion(SourceVersion.RELEASE_17)
public class FtcPlusProcessor extends AbstractProcessor {

    private boolean generated = false;

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (generated) return true;

        List<String> robots      = new ArrayList<>();
        List<String> settings    = new ArrayList<>();
        List<String> diagnostics = new ArrayList<>();

        // @TeamRobot — collect class names
        for (Element el : roundEnv.getElementsAnnotatedWith(
                processingEnv.getElementUtils().getTypeElement("dev.ftcplus.core.TeamRobot"))) {
            if (el.getKind() == ElementKind.CLASS) {
                robots.add(((TypeElement) el).getQualifiedName().toString());
            }
        }

        // @Setting — collect class#field
        for (Element el : roundEnv.getElementsAnnotatedWith(
                processingEnv.getElementUtils().getTypeElement("dev.ftcplus.core.Setting"))) {
            if (el.getKind() == ElementKind.FIELD) {
                String className = ((TypeElement) el.getEnclosingElement()).getQualifiedName().toString();
                settings.add(className + "#" + el.getSimpleName());
            }
        }

        // @Diagnostic — collect class#method
        for (Element el : roundEnv.getElementsAnnotatedWith(
                processingEnv.getElementUtils().getTypeElement("dev.ftcplus.core.Diagnostic"))) {
            if (el.getKind() == ElementKind.METHOD) {
                String className = ((TypeElement) el.getEnclosingElement()).getQualifiedName().toString();
                diagnostics.add(className + "#" + el.getSimpleName());
            }
        }

        if (roundEnv.processingOver()) {
            generateRegistry(robots, settings, diagnostics);
            generated = true;
        }

        return true;
    }

    private void generateRegistry(List<String> robots, List<String> settings, List<String> diagnostics) {
        try {
            JavaFileObject file = processingEnv.getFiler()
                    .createSourceFile("dev.ftcplus.generated.FtcPlusRegistry");

            try (PrintWriter w = new PrintWriter(file.openWriter())) {
                w.println("package dev.ftcplus.generated;");
                w.println();
                w.println("// AUTO-GENERATED by FTC+ annotation processor. Do not edit.");
                w.println("public final class FtcPlusRegistry {");
                w.println();
                w.println("    private FtcPlusRegistry() {}");
                w.println();

                // robots
                w.println("    public static Class<?>[] getRobots() {");
                w.println("        return new Class<?>[] {");
                for (String c : robots) {
                    w.println("            " + c + ".class,");
                }
                w.println("        };");
                w.println("    }");
                w.println();

                // settings
                w.println("    public static String[] getSettingFields() {");
                w.println("        return new String[] {");
                for (String s : settings) {
                    w.println("            \"" + s + "\",");
                }
                w.println("        };");
                w.println("    }");
                w.println();

                // diagnostics
                w.println("    public static String[] getDiagnosticMethods() {");
                w.println("        return new String[] {");
                for (String d : diagnostics) {
                    w.println("            \"" + d + "\",");
                }
                w.println("        };");
                w.println("    }");
                w.println("}");
            }
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(
                javax.tools.Diagnostic.Kind.ERROR,
                "FTC+ annotation processor failed: " + e.getMessage()
            );
        }
    }
}