package dev.ftcplus.core;

public enum GamepadAxis {
    G1_LEFT_STICK_X, G1_LEFT_STICK_Y,
    G1_RIGHT_STICK_X, G1_RIGHT_STICK_Y,
    G1_LEFT_TRIGGER, G1_RIGHT_TRIGGER,
    G1_TOUCHPAD_1_X, G1_TOUCHPAD_1_Y,
    G1_TOUCHPAD_2_X, G1_TOUCHPAD_2_Y,

    G2_LEFT_STICK_X, G2_LEFT_STICK_Y,
    G2_RIGHT_STICK_X, G2_RIGHT_STICK_Y,
    G2_LEFT_TRIGGER, G2_RIGHT_TRIGGER,
    G2_TOUCHPAD_1_X, G2_TOUCHPAD_1_Y,
    G2_TOUCHPAD_2_X, G2_TOUCHPAD_2_Y
}